const tokens = [
  {
    id: "btc",
    name: "Bitcoin",
    symbol: "BTC",
    balance: 0.05,
    price: 60000,
    change: 2.5,
    color: "#F7931A",
  },
  {
    id: "eth",
    name: "Ethereum",
    symbol: "ETH",
    balance: 0.75,
    price: 2800,
    change: -1.2,
    color: "#627EEA",
  },
  {
    id: "sol",
    name: "Solana",
    symbol: "SOL",
    balance: 10,
    price: 120,
    change: 5.8,
    color: "#14F195",
  },
  {
    id: "usdc",
    name: "USD Coin",
    symbol: "USDC",
    balance: 500,
    price: 1,
    change: 0,
    color: "#2775CA",
  },
  // {
  //   id: "lcra",
  //   name: "Lucra",
  //   symbol: "LCRA",
  //   balance: 1000,
  //   price: 0.03,
  //   change: 10.5,
  //   color: "#4AE3A8",
  // },
];
